### ISSUE TITLE
Seeds fail with NoMethodError: undefined method `logos' for #<Theme:0x0000560e0efa5060>

### ISSUE THREAD

**Issue by lauramosher** [Terrastories/terrastories#568]
**Describe the bug**

When setting up the app or resetting using `bin/setup`, or when seeding the database, the following error occurs:

```
rails aborted!
NoMethodError: undefined method `logos' for #<Theme:0x0000560e0efa5060>
/usr/local/bundle/gems/activemodel-5.2.4.3/lib/active_model/attribute_methods.rb:430:in `method_missing'
/opt/terrastories/db/seeds.rb:87:in `block in <top (required)>'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/core.rb:317:in `initialize'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/inheritance.rb:66:in `new'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/inheritance.rb:66:in `new'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/persistence.rb:52:in `create!'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:99:in `block in create!'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:281:in `scoping'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:99:in `create!'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:171:in `find_or_create_by!'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/querying.rb:8:in `find_or_create_by!'
/opt/terrastories/db/seeds.rb:85:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `block in load'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/engine.rb:554:in `block in load_seed'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/engine.rb:672:in `with_inline_jobs'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/engine.rb:554:in `load_seed'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/usr/local/bundle/gems/activerecord-5.2.4.3/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)

== Command ["bin/rails db:setup"] failed ==
```

**To Reproduce**

1. run `docker-compose exec web bin/setup`
2. see error

**Expected behavior**

Seed step should pass and the setup script should complete successfully.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: n/a
 - Version: latest master

**Smartphone (please complete the following information):**

n/a

**Additional context**

n/a

**Comment by lauramosher** [comment]
fixed in https://github.com/Terrastories/terrastories/pull/567
